name = "bendragon"
compatibility_date = "2025-10-08"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Cloudflare D1 Database binding for Ben & Dragon! Character Sheets
[[d1_databases]]
binding = "DB"
database_name = "bendragonDB"
database_id = "bendragonDB"

[[d1_databases]]
binding = "bendragonDB"
database_name = "bendragonDB"
database_id = "bendragonDB"

[vars]

# DATABASE_URL = "postgres://user:password@hostname:5432/dbname?sslmode=require"
